server:
    port: 8083
    servlet:
        contextPath: /foodWebsite
spring:
    datasource:
        password: SiMargAlex2022
        url: jdbc:mysql://localhost:3306/foodwebsite?user=root
        driverClassName: com.mysql.cj.jdbc.Driver